### ISSUE TITLE
Add tokens to UI

### ISSUE THREAD

**Issue by green-jay** [galacticcouncil/ui#3]
UNQ -> wallet + cross-chain
![unique-logo-short](https://github.com/galacticcouncil/HydraDX-ui/assets/75261756/7d35a2d4-441a-4093-aa12-492006bb098d)

PHA -> icon already in wallet, use the same for cross-chain

NODL -> wallet + cross-chain
![NodleLogo2023_Aqua](https://github.com/galacticcouncil/HydraDX-ui/assets/75261756/95507d52-4a47-4753-b614-a3364d967d72)

SUB -> change white chain icon to purple one
![Subsocial sign w white S](https://github.com/galacticcouncil/HydraDX-ui/assets/75261756/6e34c7bf-3bc3-482f-b943-a90a49ee661b)

**Comment by nohaapav** [comment]
in master

**Comment by green-jay** [comment]
reopening, icons not in cross-chain
